image: mischief/docker-golang
env:
  - GOPATH=/var/cache/drone
script:
  - apt-get install unzip python-imaging
  - wget https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.8.zip -nv
  - unzip -q go_appengine_sdk_linux_amd64-1.9.8.zip
  - go_appengine/goapp test -v
